
#port config
server:
  port: 8005
#appilication base info config
spring:
  application:
    name: server-eureka
#eurake config self not to register to eureka server
eureka:
  server:
    eviction-interval-timer-in-ms: 20000 # 设置清理的间隔时间，毫秒单位（默认是60秒）
  instance:
    hostname: htd-08011390.htd.com #服务注册中心配置的是主机名或者localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: true # 当前服务是否注册到eureka上 true 注册 false 不注册
    fetch-registry: true # 是否通过eureka获取注册信息 true 获取 false 不获取
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
